In [ ]:
AAPL -1

In [2]:
from yahoo_fin import stock_info as si
from datetime import datetime, timedelta

In [69]:
si.tickers_sp500()

['A',
 'AAL',
 'AAP',
 'AAPL',
 'ABBV',
 'ABC',
 'ABMD',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'AEE',
 'AEP',
 'AES',
 'AFL',
 'AIG',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALK',
 'ALL',
 'ALLE',
 'AMAT',
 'AMCR',
 'AMD',
 'AME',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'ANET',
 'ANSS',
 'AON',
 'AOS',
 'APA',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ATO',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AZO',
 'BA',
 'BAC',
 'BALL',
 'BAX',
 'BBWI',
 'BBY',
 'BDX',
 'BEN',
 'BF-B',
 'BIIB',
 'BIO',
 'BK',
 'BKNG',
 'BKR',
 'BLK',
 'BMY',
 'BR',
 'BRK-B',
 'BRO',
 'BSX',
 'BWA',
 'BXP',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CBOE',
 'CBRE',
 'CCI',
 'CCL',
 'CDAY',
 'CDNS',
 'CDW',
 'CE',
 'CEG',
 'CF',
 'CFG',
 'CHD',
 'CHRW',
 'CHTR',
 'CI',
 'CINF',
 'CL',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COO',
 'COP',
 'COST',
 'CPB',
 'CPRT',
 'CPT',
 'CRL',
 'CRM',
 'CSCO',
 'CSGP',
 'CSX',
 'CTAS',
 'CTLT',
 'CTRA',
 'CTSH',
 'CTVA',
 'CVS',
 'CVX',
 'CZR',
 'D',
 'DAL',
 'DD',
 'DE',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DISH',
 'DLR',
 'DLTR',
 'DOV',
 'DOW',
 'DPZ',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DXC',
 'DXCM',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'ELV',
 'EMN',
 'EMR',
 'ENPH',
 'EOG',
 'EPAM',
 'EQIX',
 'EQR',
 'EQT',
 'ES',
 'ESS',
 'ETN',
 'ETR',
 'ETSY',
 'EVRG',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FANG',
 'FAST',
 'FBHS',
 'FCX',
 'FDS',
 'FDX',
 'FE',
 'FFIV',
 'FIS',
 'FISV',
 'FITB',
 'FLT',
 'FMC',
 'FOX',
 'FOXA',
 'FRC',
 'FRT',
 'FTNT',
 'FTV',
 'GD',
 'GE',
 'GILD',
 'GIS',
 'GL',
 'GLW',
 'GM',
 'GNRC',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GRMN',
 'GS',
 'GWW',
 'HAL',
 'HAS',
 'HBAN',
 'HCA',
 'HD',
 'HES',
 'HIG',
 'HII',
 'HLT',
 'HOLX',
 'HON',
 'HPE',
 'HPQ',
 'HRL',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'IDXX',
 'IEX',
 'IFF',
 'ILMN',
 'INCY',
 'INTC',
 'INTU',
 'INVH',
 'IP',
 'IPG',
 'IQV',
 'IR',
 'IRM',
 'ISRG',
 'IT',
 'ITW',
 'IVZ',
 'J',
 'JBHT',
 'JCI',
 'JKHY',
 'JNJ',
 'JNPR',
 'JPM',
 'K',
 'KDP',
 'KEY',
 'KEYS',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'L',
 'LDOS',
 'LEN',
 'LH',
 'LHX',
 'LIN',
 'LKQ',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LUMN',
 'LUV',
 'LVS',
 'LW',
 'LYB',
 'LYV',
 'MA',
 'MAA',
 'MAR',
 'MAS',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'META',
 'MGM',
 'MHK',
 'MKC',
 'MKTX',
 'MLM',
 'MMC',
 'MMM',
 'MNST',
 'MO',
 'MOH',
 'MOS',
 'MPC',
 'MPWR',
 'MRK',
 'MRNA',
 'MRO',
 'MS',
 'MSCI',
 'MSFT',
 'MSI',
 'MTB',
 'MTCH',
 'MTD',
 'MU',
 'NCLH',
 'NDAQ',
 'NDSN',
 'NEE',
 'NEM',
 'NFLX',
 'NI',
 'NKE',
 'NLOK',
 'NOC',
 'NOW',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NVR',
 'NWL',
 'NWS',
 'NWSA',
 'NXPI',
 'O',
 'ODFL',
 'OGN',
 'OKE',
 'OMC',
 'ON',
 'ORCL',
 'ORLY',
 'OTIS',
 'OXY',
 'PARA',
 'PAYC',
 'PAYX',
 'PCAR',
 'PCG',
 'PEAK',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKG',
 'PKI',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'POOL',
 'PPG',
 'PPL',
 'PRU',
 'PSA',
 'PSX',
 'PTC',
 'PWR',
 'PXD',
 'PYPL',
 'QCOM',
 'QRVO',
 'RCL',
 'RE',
 'REG',
 'REGN',
 'RF',
 'RHI',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RSG',
 'RTX',
 'SBAC',
 'SBNY',
 'SBUX',
 'SCHW',
 'SEDG',
 'SEE',
 'SHW',
 'SIVB',
 'SJM',
 'SLB',
 'SNA',
 'SNPS',
 'SO',
 'SPG',
 'SPGI',
 'SRE',
 'STE',
 'STT',
 'STX',
 'STZ',
 'SWK',
 'SWKS',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TAP',
 'TDG',
 'TDY',
 'TECH',
 'TEL',
 'TER',
 'TFC',
 'TFX',
 'TGT',
 'TJX',
 'TMO',
 'TMUS',
 'TPR',
 'TRGP',
 'TRMB',
 'TROW',
 'TRV',
 'TSCO',
 'TSLA',
 'TSN',
 'TT',
 'TTWO',
 'TWTR',
 'TXN',
 'TXT',
 'TYL',
 'UAL',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNP',
 'UPS',
 'URI',
 'USB',
 'V',
 'VFC',
 'VICI',
 'VLO',
 'VMC',
 'VNO',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VTRS',
 'VZ',
 'WAB',
 'WAT',
 'WBA',
 'WBD',
 'WDC',
 'WEC',
 'WELL',
 'WFC',
 'WHR',
 'WM',
 'WMB',
 'WMT',
 'WRB',
 'WRK',
 'WST',
 'WTW',
 'WY',
 'WYNN',
 'XEL',
 'XOM',
 'XRAY',
 'XYL',
 'YUM',
 'ZBH',
 'ZBRA',
 'ZION',
 'ZTS']

In [35]:
now = datetime.now()
data_points = 30
lag = round(data_points / 5 * 7,0)
print(lag)
display(si.get_data('AAPL','2022-01-01','2022-10-01',index_as_date=False))

42.0

,date,open,high,low,close,adjclose,volume,ticker
0,2022-01-03,177.830002,182.880005,177.710007,182.009995,181.259933,104487900,AAPL
1,2022-01-04,182.630005,182.940002,179.119995,179.699997,178.959457,99310400,AAPL
2,2022-01-05,179.610001,180.169998,174.639999,174.919998,174.199142,94537600,AAPL
3,2022-01-06,172.699997,175.300003,171.639999,172.000000,171.291183,96904000,AAPL
4,2022-01-07,172.889999,174.139999,171.029999,172.169998,171.460495,86709100,AAPL
...,...,...,...,...,...,...,...,...
183,2022-09-26,149.660004,153.770004,149.639999,150.770004,150.770004,93339400,AAPL
184,2022-09-27,152.740005,154.720001,149.949997,151.759995,151.759995,84442700,AAPL
185,2022-09-28,147.639999,150.639999,144.839996,149.839996,149.839996,146691400,AAPL
186,2022-09-29,146.100006,146.720001,140.679993,142.479996,142.479996,128138200,AAPL
187,2022-09-30,141.279999,143.100006,138.000000,138.199997,138.199997,124705400,AAPL

In [37]:
def get_ticker_data(ticker=None, lag=None):
    if ticker==None:
        return f'No ticker provided to get_ticker_data function'
    else:
        if lag is None:
            df = si.get_data(ticker,index_as_date=False)
        else:
            df = si.get_data(ticker,index_as_date=False).tail(lag)
        return df

In [39]:
display(get_ticker_data('AAPL',30))

,date,open,high,low,close,adjclose,volume,ticker
10520,2022-09-02,159.750000,160.360001,154.970001,155.809998,155.809998,76905200,AAPL
10521,2022-09-06,156.470001,157.089996,153.690002,154.529999,154.529999,73714800,AAPL
10522,2022-09-07,154.820007,156.669998,153.610001,155.960007,155.960007,87449600,AAPL
10523,2022-09-08,154.639999,156.360001,152.679993,154.460007,154.460007,84923800,AAPL
10524,2022-09-09,155.470001,157.820007,154.750000,157.369995,157.369995,68028800,AAPL
10525,2022-09-12,159.589996,164.259995,159.300003,163.429993,163.429993,104956000,AAPL
10526,2022-09-13,159.899994,160.539993,153.369995,153.839996,153.839996,122656600,AAPL
10527,2022-09-14,154.789993,157.100006,153.610001,155.309998,155.309998,87965400,AAPL
10528,2022-09-15,154.649994,155.240005,151.380005,152.369995,152.369995,90481100,AAPL
10529,2022-09-16,151.210007,151.350006,148.369995,150.699997,150.699997,162157000,AAPL
10530,2022-09-19,149.309998,154.559998,149.100006,154.479996,154.479996,81474200,AAPL
10531,2022-09-20,153.399994,158.080002,153.080002,156.899994,156.899994,107689800,AAPL
10532,2022-09-21,157.339996,158.740005,153.600006,153.720001,153.720001,101696800,AAPL
10533,2022-09-22,152.380005,154.470001,150.910004,152.740005,152.740005,86652500,AAPL
10534,2022-09-23,151.190002,151.470001,148.559998,150.429993,150.429993,95939200,AAPL
10535,2022-09-26,149.660004,153.770004,149.639999,150.770004,150.770004,93339400,AAPL
10536,2022-09-27,152.740005,154.720001,149.949997,151.759995,151.759995,84442700,AAPL
10537,2022-09-28,147.639999,150.639999,144.839996,149.839996,149.839996,146691400,AAPL
10538,2022-09-29,146.100006,146.720001,140.679993,142.479996,142.479996,128138200,AAPL
10539,2022-09-30,141.279999,143.100006,138.000000,138.199997,138.199997,124705400,AAPL
10540,2022-10-03,138.210007,143.070007,137.690002,142.449997,142.449997,114311700,AAPL
10541,2022-10-04,145.029999,146.220001,144.259995,146.100006,146.100006,87830100,AAPL
10542,2022-10-05,144.070007,147.380005,143.009995,146.399994,146.399994,79471000,AAPL
10543,2022-10-06,145.809998,147.539993,145.220001,145.429993,145.429993,68402200,AAPL
10544,2022-10-07,142.539993,143.100006,139.449997,140.089996,140.089996,85859100,AAPL
10545,2022-10-10,140.419998,141.889999,138.570007,140.419998,140.419998,74899000,AAPL
10546,2022-10-11,139.899994,141.350006,138.220001,138.979996,138.979996,77033700,AAPL
10547,2022-10-12,139.130005,140.360001,138.160004,138.339996,138.339996,70433700,AAPL
10548,2022-10-13,134.990005,143.589996,134.369995,142.990005,142.990005,113224000,AAPL
10549,2022-10-14,144.309998,144.520004,138.190002,138.380005,138.380005,88512300,AAPL

In [53]:
df1 = get_ticker_data('AAPL',30)

In [67]:
df2 = df1['close'].fillna(method = 'bfill').reset_index().drop(columns='index').T
display(df2)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
close,155.809998,154.529999,155.960007,154.460007,157.369995,163.429993,153.839996,155.309998,152.369995,150.699997,...,142.449997,146.100006,146.399994,145.429993,140.089996,140.419998,138.979996,138.339996,142.990005,138.380005

In [58]:
df3 = df2.drop(columns='index')
display(df3)

         close
0   155.809998
1   154.529999
2   155.960007
3   154.460007
4   157.369995
5   163.429993
6   153.839996
7   155.309998
8   152.369995
9   150.699997
10  154.479996
11  156.899994
12  153.720001
13  152.740005
14  150.429993
15  150.770004
16  151.759995
17  149.839996
18  142.479996
19  138.199997
20  142.449997
21  146.100006
22  146.399994
23  145.429993
24  140.089996
25  140.419998
26  138.979996
27  138.339996
28  142.990005
29  138.380005

In [15]:
def get_ticker_data(ticker=None, lag=None):
    if ticker is None:
        return f'No ticker provided to get_ticker_data function'
    else:
        if lag is None:
            df = si.get_data(ticker, index_as_date=False)
        else:
            df = si.get_data(ticker , index_as_date=False).tail(lag)
        return df
    
def create_prediction_input(df):
    x_predict = df['close'].fillna(method='bfill').reset_index().drop(columns='index').diff().dropna().T

    return x_predict

In [7]:
import joblib

In [8]:
model = joblib.load('mdl.sav')

In [6]:
y_pred = model.predict(create_prediction_input(get_ticker_data('AAPL',31)))
print(y_pred)

[1.]

In [122]:
df_tst = get_ticker_data('AAPL',31)

In [125]:
x_predict = df_tst['close'].fillna(method='bfill').reset_index().drop(columns='index').diff().dropna().T
display(x_predict)

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
close,-0.219986,2.329987,-0.169998,-0.809998,-4.630005,1.090012,-6.080002,-0.229996,7.069992,-5.990005,...,-1.570007,3.700012,-8.419998,-3.470001,0.23999,5.520004,-2.75,0.160004,3.259995,5.860001

In [16]:
results = []
for x in si.tickers_sp500():
    y_pred = model.predict(create_prediction_input(get_ticker_data(x,31)))
    results.append([x,y_pred[0]])

In [17]:
display(results)

[['A', 1.0],
 ['AAL', 1.0],
 ['AAP', 1.0],
 ['AAPL', 1.0],
 ['ABBV', 1.0],
 ['ABC', 1.0],
 ['ABMD', 1.0],
 ['ABT', 1.0],
 ['ACN', 1.0],
 ['ADBE', 1.0],
 ['ADI', 1.0],
 ['ADM', 1.0],
 ['ADP', 1.0],
 ['ADSK', 1.0],
 ['AEE', 1.0],
 ['AEP', 1.0],
 ['AES', 1.0],
 ['AFL', 1.0],
 ['AIG', 1.0],
 ['AIZ', 1.0],
 ['AJG', 1.0],
 ['AKAM', 1.0],
 ['ALB', 1.0],
 ['ALGN', 1.0],
 ['ALK', 1.0],
 ['ALL', 1.0],
 ['ALLE', 1.0],
 ['AMAT', 1.0],
 ['AMCR', 1.0],
 ['AMD', 1.0],
 ['AME', 1.0],
 ['AMGN', 1.0],
 ['AMP', 1.0],
 ['AMT', 1.0],
 ['AMZN', 1.0],
 ['ANET', 1.0],
 ['ANSS', 1.0],
 ['AON', 1.0],
 ['AOS', 1.0],
 ['APA', 1.0],
 ['APD', 1.0],
 ['APH', 1.0],
 ['APTV', 1.0],
 ['ARE', 1.0],
 ['ATO', 1.0],
 ['ATVI', 1.0],
 ['AVB', 1.0],
 ['AVGO', 1.0],
 ['AVY', 1.0],
 ['AWK', 1.0],
 ['AXP', 1.0],
 ['AZO', -1.0],
 ['BA', 1.0],
 ['BAC', 1.0],
 ['BALL', 1.0],
 ['BAX', 1.0],
 ['BBWI', 1.0],
 ['BBY', 1.0],
 ['BDX', 1.0],
 ['BEN', 1.0],
 ['BF-B', 1.0],
 ['BIIB', -1.0],
 ['BIO', 1.0],
 ['BK', 1.0],
 ['BKNG', 1.0],
 ['BKR', 1.0],
 ['BLK', 1.0],
 ['BMY', 1.0],
 ['BR', 1.0],
 ['BRK-B', 1.0],
 ['BRO', 1.0],
 ['BSX', 1.0],
 ['BWA', 1.0],
 ['BXP', 1.0],
 ['C', 1.0],
 ['CAG', 1.0],
 ['CAH', 1.0],
 ['CARR', 1.0],
 ['CAT', 1.0],
 ['CB', 1.0],
 ['CBOE', 1.0],
 ['CBRE', 1.0],
 ['CCI', 1.0],
 ['CCL', 1.0],
 ['CDAY', 1.0],
 ['CDNS', 1.0],
 ['CDW', 1.0],
 ['CE', 1.0],
 ['CEG', 1.0],
 ['CF', 1.0],
 ['CFG', 1.0],
 ['CHD', 1.0],
 ['CHRW', 1.0],
 ['CHTR', 1.0],
 ['CI', 1.0],
 ['CINF', 1.0],
 ['CL', 1.0],
 ['CLX', 1.0],
 ['CMA', 1.0],
 ['CMCSA', 1.0],
 ['CME', 1.0],
 ['CMG', 1.0],
 ['CMI', 1.0],
 ['CMS', 1.0],
 ['CNC', 1.0],
 ['CNP', 1.0],
 ['COF', 1.0],
 ['COO', 1.0],
 ['COP', 1.0],
 ['COST', 1.0],
 ['CPB', 1.0],
 ['CPRT', 1.0],
 ['CPT', 1.0],
 ['CRL', 1.0],
 ['CRM', 1.0],
 ['CSCO', 1.0],
 ['CSGP', 1.0],
 ['CSX', 1.0],
 ['CTAS', 1.0],
 ['CTLT', 1.0],
 ['CTRA', 1.0],
 ['CTSH', 1.0],
 ['CTVA', 1.0],
 ['CVS', 1.0],
 ['CVX', 1.0],
 ['CZR', 1.0],
 ['D', 1.0],
 ['DAL', 1.0],
 ['DD', 1.0],
 ['DE', 1.0],
 ['DFS', 1.0],
 ['DG', 1.0],
 ['DGX', 1.0],
 ['DHI', 1.0],
 ['DHR', 1.0],
 ['DIS', 1.0],
 ['DISH', 1.0],
 ['DLR', 1.0],
 ['DLTR', 1.0],
 ['DOV', 1.0],
 ['DOW', 1.0],
 ['DPZ', 1.0],
 ['DRI', 1.0],
 ['DTE', 1.0],
 ['DUK', 1.0],
 ['DVA', 1.0],
 ['DVN', 1.0],
 ['DXC', 1.0],
 ['DXCM', 1.0],
 ['EA', 1.0],
 ['EBAY', 1.0],
 ['ECL', 1.0],
 ['ED', 1.0],
 ['EFX', 1.0],
 ['EIX', 1.0],
 ['EL', 1.0],
 ['ELV', 1.0],
 ['EMN', 1.0],
 ['EMR', 1.0],
 ['ENPH', 1.0],
 ['EOG', 1.0],
 ['EPAM', 1.0],
 ['EQIX', 1.0],
 ['EQR', 1.0],
 ['EQT', 1.0],
 ['ES', 1.0],
 ['ESS', 1.0],
 ['ETN', 1.0],
 ['ETR', 1.0],
 ['ETSY', 1.0],
 ['EVRG', 1.0],
 ['EW', 1.0],
 ['EXC', 1.0],
 ['EXPD', 1.0],
 ['EXPE', 1.0],
 ['EXR', 1.0],
 ['F', 1.0],
 ['FANG', 1.0],
 ['FAST', 1.0],
 ['FBHS', 1.0],
 ['FCX', 1.0],
 ['FDS', 1.0],
 ['FDX', -1.0],
 ['FE', 1.0],
 ['FFIV', 1.0],
 ['FIS', 1.0],
 ['FISV', 1.0],
 ['FITB', 1.0],
 ['FLT', 1.0],
 ['FMC', 1.0],
 ['FOX', 1.0],
 ['FOXA', 1.0],
 ['FRC', 1.0],
 ['FRT', 1.0],
 ['FTNT', 1.0],
 ['FTV', 1.0],
 ['GD', 1.0],
 ['GE', 1.0],
 ['GILD', 1.0],
 ['GIS', 1.0],
 ['GL', 1.0],
 ['GLW', 1.0],
 ['GM', 1.0],
 ['GNRC', 1.0],
 ['GOOG', 1.0],
 ['GOOGL', 1.0],
 ['GPC', 1.0],
 ['GPN', 1.0],
 ['GRMN', 1.0],
 ['GS', 1.0],
 ['GWW', 1.0],
 ['HAL', 1.0],
 ['HAS', 1.0],
 ['HBAN', 1.0],
 ['HCA', 1.0],
 ['HD', 1.0],
 ['HES', 1.0],
 ['HIG', 1.0],
 ['HII', 1.0],
 ['HLT', 1.0],
 ['HOLX', 1.0],
 ['HON', 1.0],
 ['HPE', 1.0],
 ['HPQ', 1.0],
 ['HRL', 1.0],
 ['HSIC', 1.0],
 ['HST', 1.0],
 ['HSY', 1.0],
 ['HUM', -1.0],
 ['HWM', 1.0],
 ['IBM', 1.0],
 ['ICE', 1.0],
 ['IDXX', 1.0],
 ['IEX', 1.0],
 ['IFF', 1.0],
 ['ILMN', 1.0],
 ['INCY', 1.0],
 ['INTC', 1.0],
 ['INTU', 1.0],
 ['INVH', 1.0],
 ['IP', 1.0],
 ['IPG', 1.0],
 ['IQV', 1.0],
 ['IR', 1.0],
 ['IRM', 1.0],
 ['ISRG', 1.0],
 ['IT', 1.0],
 ['ITW', 1.0],
 ['IVZ', 1.0],
 ['J', 1.0],
 ['JBHT', 1.0],
 ['JCI', 1.0],
 ['JKHY', 1.0],
 ['JNJ', 1.0],
 ['JNPR', 1.0],
 ['JPM', 1.0],
 ['K', 1.0],
 ['KDP', 1.0],
 ['KEY', 1.0],
 ['KEYS', 1.0],
 ['KHC', 1.0],
 ['KIM', 1.0],
 ['KLAC', 1.0],
 ['KMB', 1.0],
 ['KMI', 1.0],
 ['KMX', 1.0],
 ['KO', 1.0],
 ['KR', 1.0],
 ['L', 1.0],
 ['LDOS', 1.0],
 ['LEN', 1.0],
 ['LH', 1.0],
 ['LHX', 1.0],
 ['LIN', 1.0],
 ['LKQ', 1.0],
 ['LLY', 1.0],
 ['LMT', 1.0],
 ['LNC', 1.0],
 ['LNT', 1.0],
 ['LOW', 1.0],
 ['LRCX', 1.0],
 ['LUMN', 1.0],
 ['LUV', 1.0],
 ['LVS', 1.0],
 ['LW', 1.0],
 ['LYB', 1.0],
 ['LYV', 1.0],
 ['MA', 1.0],
 ['MAA', 1.0],
 ['MAR', 1.0],
 ['MAS', 1.0],
 ['MCD', 1.0],
 ['MCHP', 1.0],
 ['MCK', 1.0],
 ['MCO', 1.0],
 ['MDLZ', 1.0],
 ['MDT', 1.0],
 ['MET', 1.0],
 ['META', 1.0],
 ['MGM', 1.0],
 ['MHK', 1.0],
 ['MKC', 1.0],
 ['MKTX', 1.0],
 ['MLM', 1.0],
 ['MMC', 1.0],
 ['MMM', 1.0],
 ['MNST', 1.0],
 ['MO', 1.0],
 ['MOH', 1.0],
 ['MOS', 1.0],
 ['MPC', 1.0],
 ['MPWR', 1.0],
 ['MRK', 1.0],
 ['MRNA', 1.0],
 ['MRO', 1.0],
 ['MS', 1.0],
 ['MSCI', 1.0],
 ['MSFT', 1.0],
 ['MSI', 1.0],
 ['MTB', 1.0],
 ['MTCH', 1.0],
 ['MTD', 1.0],
 ['MU', 1.0],
 ['NCLH', 1.0],
 ['NDAQ', 1.0],
 ['NDSN', 1.0],
 ['NEE', 1.0],
 ['NEM', 1.0],
 ['NFLX', 1.0],
 ['NI', 1.0],
 ['NKE', 1.0],
 ['NLOK', 1.0],
 ['NOC', 1.0],
 ['NOW', 1.0],
 ['NRG', 1.0],
 ['NSC', 1.0],
 ['NTAP', 1.0],
 ['NTRS', 1.0],
 ['NUE', 1.0],
 ['NVDA', 1.0],
 ['NVR', 1.0],
 ['NWL', 1.0],
 ['NWS', 1.0],
 ['NWSA', 1.0],
 ['NXPI', 1.0],
 ['O', 1.0],
 ['ODFL', 1.0],
 ['OGN', 1.0],
 ['OKE', 1.0],
 ['OMC', 1.0],
 ['ON', 1.0],
 ['ORCL', 1.0],
 ['ORLY', 1.0],
 ['OTIS', 1.0],
 ['OXY', 1.0],
 ['PARA', 1.0],
 ['PAYC', 1.0],
 ['PAYX', 1.0],
 ['PCAR', 1.0],
 ['PCG', 1.0],
 ['PEAK', 1.0],
 ['PEG', 1.0],
 ['PEP', 1.0],
 ['PFE', 1.0],
 ['PFG', 1.0],
 ['PG', 1.0],
 ['PGR', 1.0],
 ['PH', 1.0],
 ['PHM', 1.0],
 ['PKG', 1.0],
 ['PKI', 1.0],
 ['PLD', 1.0],
 ['PM', 1.0],
 ['PNC', 1.0],
 ['PNR', 1.0],
 ['PNW', 1.0],
 ['POOL', 1.0],
 ['PPG', 1.0],
 ['PPL', 1.0],
 ['PRU', 1.0],
 ['PSA', 1.0],
 ['PSX', 1.0],
 ['PTC', 1.0],
 ['PWR', 1.0],
 ['PXD', 1.0],
 ['PYPL', 1.0],
 ['QCOM', 1.0],
 ['QRVO', 1.0],
 ['RCL', 1.0],
 ['RE', 1.0],
 ['REG', 1.0],
 ['REGN', 1.0],
 ['RF', 1.0],
 ['RHI', 1.0],
 ['RJF', 1.0],
 ['RL', 1.0],
 ['RMD', 1.0],
 ['ROK', 1.0],
 ['ROL', 1.0],
 ['ROP', 1.0],
 ['ROST', 1.0],
 ['RSG', 1.0],
 ['RTX', 1.0],
 ['SBAC', 1.0],
 ['SBNY', 1.0],
 ['SBUX', 1.0],
 ['SCHW', 1.0],
 ['SEDG', 1.0],
 ['SEE', 1.0],
 ['SHW', 1.0],
 ['SIVB', 1.0],
 ['SJM', 1.0],
 ['SLB', 1.0],
 ['SNA', 1.0],
 ['SNPS', 1.0],
 ['SO', 1.0],
 ['SPG', 1.0],
 ['SPGI', 1.0],
 ['SRE', 1.0],
 ['STE', 1.0],
 ['STT', 1.0],
 ['STX', 1.0],
 ['STZ', 1.0],
 ['SWK', 1.0],
 ['SWKS', 1.0],
 ['SYF', 1.0],
 ['SYK', 1.0],
 ['SYY', 1.0],
 ['T', 1.0],
 ['TAP', 1.0],
 ['TDG', 1.0],
 ['TDY', 1.0],
 ['TECH', 1.0],
 ['TEL', 1.0],
 ['TER', 1.0],
 ['TFC', 1.0],
 ['TFX', 1.0],
 ['TGT', 1.0],
 ['TJX', 1.0],
 ['TMO', 1.0],
 ['TMUS', 1.0],
 ['TPR', 1.0],
 ['TRGP', 1.0],
 ['TRMB', 1.0],
 ['TROW', 1.0],
 ['TRV', 1.0],
 ['TSCO', 1.0],
 ['TSLA', 1.0],
 ['TSN', 1.0],
 ['TT', 1.0],
 ['TTWO', 1.0],
 ['TWTR', 1.0],
 ['TXN', 1.0],
 ['TXT', 1.0],
 ['TYL', 1.0],
 ['UAL', 1.0],
 ['UDR', 1.0],
 ['UHS', 1.0],
 ['ULTA', 1.0],
 ['UNH', 1.0],
 ['UNP', 1.0],
 ['UPS', 1.0],
 ['URI', 1.0],
 ['USB', 1.0],
 ['V', 1.0],
 ['VFC', 1.0],
 ['VICI', 1.0],
 ['VLO', 1.0],
 ['VMC', 1.0],
 ['VNO', 1.0],
 ['VRSK', 1.0],
 ['VRSN', 1.0],
 ['VRTX', 1.0],
 ['VTR', 1.0],
 ['VTRS', 1.0],
 ['VZ', 1.0],
 ['WAB', 1.0],
 ['WAT', 1.0],
 ['WBA', 1.0],
 ['WBD', 1.0],
 ['WDC', 1.0],
 ['WEC', 1.0],
 ['WELL', 1.0],
 ['WFC', 1.0],
 ['WHR', 1.0],
 ['WM', 1.0],
 ['WMB', 1.0],
 ['WMT', 1.0],
 ['WRB', 1.0],
 ['WRK', 1.0],
 ['WST', 1.0],
 ['WTW', 1.0],
 ['WY', 1.0],
 ['WYNN', 1.0],
 ['XEL', 1.0],
 ['XOM', 1.0],
 ['XRAY', 1.0],
 ['XYL', 1.0],
 ['YUM', 1.0],
 ['ZBH', 1.0],
 ['ZBRA', 1.0],
 ['ZION', 1.0],
 ['ZTS', 1.0]]

In [12]:
import operator as op

print(op.countOf(results,1.0))
print(op.countOf(results,-1.0))

485
18